#!/bin/sh

# MODULES_LIST="otus otusfw athp"
MODULES_LIST="athp otusfw athpfw"

for i in ${MODULES_LIST}; do
	echo "entering ${i}"
	PPWD="`pwd`"
	cd ${i} || exit 1
	../build_module $@ || exit 1
	echo ".. back to ${PPWD}"
	cd ${PPWD}
done
